### ISSUE TITLE
Allow handling of different HTTP methods

### ISSUE THREAD

**Issue by justinfagnani** [justinfagnani/route#17]

**Comment by justinfagnani** [comment]
I can see a few ways of structuring the API.

One is to add an optional parameter to serve() which a HTTP method:

```
router.serve(resourceUrl, method: GET).listen(getResource);
router.serve(resourceUrl, method: POST).listen(saveResource);
```

Another is to provide special streams that function as routers and have additional methods to filter by method:

```
router.serve(resourceUrl).get().listen(getResource);
router.serve(resourceUrl).post().listen(saveResource);
```

The first is certainly easier to implement, mainly because the central matching logic in Router can let the request fall through to other matchers or the default stream quite easily. The second approach requires some feedback from the stream that an event didn't reach a listener.

**Comment by adambender** [comment]
I personally like the first approach cause it allows us to use a similar
tactic for other headers if we want to match them later.

**Comment by adambender** [comment]
https://chromiumcodereview.appspot.com/14267030/
