### ISSUE TITLE
_MultiPattern is missing inherited member

### ISSUE THREAD

**Issue by sethladd** [justinfagnani/route#39]
Missing inherited member 'Pattern.matchAsPrefix'

Using Dart Editor version 0.5.20_r24275

**Comment by sethladd** [comment]
![screen shot 2013-06-28 at 10 24 26 pm](https://f.cloud.github.com/assets/5479/725564/25af6a66-e07c-11e2-8404-34bcbdc8066f.png)

**Comment by justinfagnani** [comment]
Fixed: https://github.com/dart-lang/route/commit/b5d62bc4c3b5deff6602ff6f5dcdee720e652e5c
