### ISSUE TITLE
UrlPattern is missing inherited member

### ISSUE THREAD

**Issue by sethladd** [justinfagnani/route#40]
Missing inherited member 'Pattern.matchAsPrefix'

Using Dart Editor version 0.5.20_r24275

**Comment by sethladd** [comment]
![screen shot 2013-06-28 at 10 23 59 pm](https://f.cloud.github.com/assets/5479/725563/1698dad0-e07c-11e2-8599-9a6a5950ca9e.png)

**Comment by justinfagnani** [comment]
Fixed: https://github.com/dart-lang/route/commit/b5d62bc4c3b5deff6602ff6f5dcdee720e652e5c
