### ISSUE TITLE
Add default handler support 

### ISSUE THREAD

**Issue by yissachar** [justinfagnani/route#42]
It would be nice to have support for a default route handler that would be invoked when no other routes were matched. For instance, something like the following:

```
 var router = new Router()
..addHandler(homeUrl, showHome)
..addHandler(articleUrl, showArticle)
..addDefaultHandler(showDefaultPlace)
..listen();
```

If the URL does not match homeUrl or articleUrl, showDefaultPlace will be called.

Currently in order to achieve this behaviour, a handler that matches all routes would have to be created and then URLs could be matched against them (as outlined in my [StackOverflow answer](http://stackoverflow.com/questions/16402381/dart-and-http-pub-dartlang-org-packages-route/16408123#16408123)). This is a messy workaround and it would be much cleaner to have built-in support.

**Comment by pavelgj** [comment]
If you're feeling adventurous take a look at this branch where default routes are already implemented: 
https://github.com/dart-lang/route/tree/experimental_hierarchical

(WARNING: as the name suggests, it is experimental, so API is subject to change without warning)

**Comment by yissachar** [comment]
Oh, very cool. Looks like this solves a few other things that I was going to complain about, so I'm looking forward to playing with it.
