### ISSUE TITLE
router matcher does not handle correctly paths with common prefix

### ISSUE THREAD

**Issue by tomaszkubacki** [justinfagnani/route#50]
eg.

router.root.addRoute(name: "book", path: "/book", enter: book );
router.root.addRoute(name: "bookings", path: "/bookings", enter: bookingList );

then go to /bookings
causes:
log: More than one route matches /bookings [[Route: book], [Route: bookings]]

**Comment by pavelgj** [comment]
You should always have the more specific route first, which would solve your problem. 

```
router.root
  ..addRoute(name: "bookings", path: "/bookings", enter: bookingList)
  ..addRoute(name: "book", path: "/book", enter: book);
```

**Comment by tomaszkubacki** [comment]
@pavelgj - this will work - however it still matches 'book' route for 'bookings' (and logs error)

**Comment by pavelgj** [comment]
I wouldn't worry about the warning. I will probably demote it to a "fine" log message instead. This is the correct behavior -- router picks the first matching route.
