### ISSUE TITLE
Add named path params

### ISSUE THREAD

**Issue by sethladd** [justinfagnani/route#52]
Something like this is common in other routing packages:

```
new UrlPattern(r'(.*)#/match/(matchId:\d+)');
```

So I can get this:

```
..addHandler(matchPath, (String path, Map options) {
  options['matchId'] ...
```

That would be great. :)

Also, I'd love to get the route options in the handler callback. Parsing it again feels weird, especially since that forces me to pull the pattern out as a variable. And I'm sure the URL was already parsed to find a match.

**Comment by justinfagnani** [comment]
Functionality like this is coming in the 0.5 branch which uses UriTemplates and named parameters.

What are "route options"?

**Comment by sethladd** [comment]
options are the name/values pulled from the URL. There's probably a better name.

**Comment by justinfagnani** [comment]
Yes, those are query parameters. UriTemplate does a much better job at this.

**Comment by sethladd** [comment]
Marking as fixed, looks like new version of route has what I need.
