### ISSUE TITLE
The router incorrectly registers top level click listener and then prevents default on all routes.

### ISSUE THREAD

**Issue by mhevery** [justinfagnani/route#69]
See: https://github.com/dart-lang/route/blob/experimental_hierarchical/lib/client.dart#L605

1) The click events should never be preventDefault() because it breaks command-click open  link in new tap in browser

2) The click listener should be on the root of the app not on window. The app can be a subset of the current view, and we should not be intercepting clicks which do not belong to  our app.

**Comment by pavelgj** [comment]
Fixed in
- https://github.com/dart-lang/route/commit/78a9a3496621c7524f01e0840cace7636f153f7b
- https://github.com/dart-lang/route/commit/6f7b893323e96a49de5348ea867480bcb90e8918

and in angular
- https://github.com/angular/angular.dart/commit/3ab250a706c84542c9e618d9e98eea81d99a5d22
