### ISSUE TITLE
What is the branching strategy of this repo ?

### ISSUE THREAD

**Issue by vicb** [justinfagnani/route#78]
Some explanations (ie in the README) would help contributors to undersatand the strategy. Quoting @pavelgj from #77 
/cc @sethladd @justinfagnani 

"""Once there was master branch in dart-lang/route. It had the original simple implementation of routing and was published to pub as route. Then experimental_hierarchical branch came into existence with the fancy hierarchical router, which was later adopted by angular.dart for which purpose it was "forked" on pub as route_hierarchical. Somewhere in between, 0.5.0 branch came into existence with an effort to make hierarchical router cleaner, easier, better. Unfortunately, it wasn't progressing very fast due to lack of time. Meanwhile, as angular.dart was adding more users maintaining route_hierarchical in a branch was getting harder and harder and decision was made to fork it to https://github.com/angular/route.dart.

As it stands right now:

master branch in dart-lang/route is the legacy (if I may, obsolete) code
experimental_hierarchical branch is frozen and moved to angular/route.dart
0.5.0 in dart-lang/route branch is possibly the future of Dart routing (we'll have to wait and see)"""

**Comment by justinfagnani** [comment]
I'll update the README, and probably just delete the entire route_hierarchical branch, since it's moved to it's own repo

**Comment by vicb** [comment]
Thanks !
